MylesMemesApp2/config/routes.rb
MylesMemesApp2::Application.routes.draw do
  get "photos/new"

  resources :memes

  root :to => 'memes#index'

end

MylesMemesApp2/app/models/meme.rb
class Meme < ActiveRecord::Base
  attr_accessible :caption, :photo
  
  has_many :photos
  
end

MylesMemesApp2/app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image
  
  belongs_to :meme
  
  mount_uploader :image, ImageUploader
end

MylesMemesApp2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

MylesMemesApp2/app/controllers/memes_controller.rb
class MemesController < ApplicationController
  # GET /memes
  # GET /memes.json
  def index
    @memes = Meme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memes }
    end
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
    @meme = Meme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meme }
    end
  end

  # GET /memes/new
  # GET /memes/new.json
  def new
    @meme = Meme.new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meme }
    
    end
  end

  # GET /memes/1/edit
  def edit
    @meme = Meme.find(params[:id])
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(params[:meme])

    respond_to do |format|
      if @meme.save
        format.html { redirect_to @meme, notice: 'Meme was successfully created.' }
        format.json { render json: @meme, status: :created, location: @meme }
      else
        format.html { render action: "new" }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memes/1
  # PUT /memes/1.json
  def update
    @meme = Meme.find(params[:id])

    respond_to do |format|
      if @meme.update_attributes(params[:meme])
        format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy

    respond_to do |format|
      format.html { redirect_to memes_url }
      format.json { head :no_content }
    end
  end
end

MylesMemesApp2/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
     @photo = Photo.new
      
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @photo }
    
    end 
  end
end

MylesMemesApp2/app/helpers/application_helper.rb
module ApplicationHelper
end

MylesMemesApp2/app/helpers/memes_helper.rb
module MemesHelper
end

MylesMemesApp2/app/helpers/photos_helper.rb
module PhotosHelper
end

MylesMemesApp2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MylesMemesApp2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MylesMemesApp2/app/views/memes/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :photo_id %>
  <p>
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>
	

  <!-- <div class="caption">
   <div class="field">
     <%=# f.label :caption %><br />
     <%=# f.text_field :caption %>
   <%# end %>
   </div> -->
 


    
  	  

MylesMemesApp2/app/views/memes/edit.html.erb
<h1>Editing meme</h1>

<%= render 'form' %>

<%= link_to 'Show', @meme %> |
<%= link_to 'Back', memes_path %>

MylesMemesApp2/app/views/memes/index.html.erb
<h1>Myles Memes</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memes.each do |meme| %>
  <tr>
    <td><%= meme.caption %></td>
    <td><%= meme.photo %></td>
    <td><%= link_to 'Show', meme %></td>
    <td><%= link_to 'Edit', edit_meme_path(meme) %></td>
    <td><%= link_to 'Destroy', meme, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meme', new_meme_path %>

MylesMemesApp2/app/views/memes/new.html.erb
<h1>New meme</h1>

<%= render 'form' %>

<%= link_to 'Back', memes_path %>

MylesMemesApp2/app/views/memes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @meme.caption %>
</p>

<p>
  <b>Photo:</b>
  <%= @photo.photo %>
</p>

<%= image_tag photo.image_url(:thumb) if photo.image? %>

<%= link_to 'Edit', edit_meme_path(@meme) %> |
<%= link_to 'Back', memes_path %>

MylesMemesApp2/app/views/photos/new.html.erb
<h1>Photos#new</h1>
<p>Find me in app/views/photos/new.html.erb</p>